// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU0Kx-2zvX1snRJRGwbFmklQgi6VHG538',
    appId: '1:251816910586:web:e3d2dad55b0369ec0ab343',
    messagingSenderId: '251816910586',
    projectId: 'chitchat-message',
    authDomain: 'chitchat-message.firebaseapp.com',
    storageBucket: 'chitchat-message.firebasestorage.app',
    measurementId: 'G-Q5FRY2TF84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj0Oa_ocmxHX1ymlzegaOwH66IgCR4w-A',
    appId: '1:251816910586:android:ef5e24c356c478ec0ab343',
    messagingSenderId: '251816910586',
    projectId: 'chitchat-message',
    storageBucket: 'chitchat-message.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmIwUQkFvv-95yTd2bYXguc8dDUU_JH58',
    appId: '1:251816910586:ios:78671df8ad507b3b0ab343',
    messagingSenderId: '251816910586',
    projectId: 'chitchat-message',
    storageBucket: 'chitchat-message.firebasestorage.app',
    iosBundleId: 'com.aniket.chitchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBU0Kx-2zvX1snRJRGwbFmklQgi6VHG538',
    appId: '1:251816910586:web:8f3aa036edafecee0ab343',
    messagingSenderId: '251816910586',
    projectId: 'chitchat-message',
    authDomain: 'chitchat-message.firebaseapp.com',
    storageBucket: 'chitchat-message.firebasestorage.app',
    measurementId: 'G-Q5D8QX6LFH',
  );
}
